# Model Constants
IMAGE_TOKEN = "<image>"
IMAGE_TOKEN_INDEX = -200
IMG_START_TOKEN   = "<img_start>"
IMG_END_TOKEN     = "<img_end>"
IGNORE_INDEX      = -100

CONTROLLER_HEART_BEAT_EXPIRATION = 30
LOGDIR = "gradio-logs"
WORKER_HEART_BEAT_INTERVAL = 15
