# Model Constants
IMAGE_TOKEN = "<image>"
IMG_START_TOKEN   = "<img_start>"
IMG_END_TOKEN     = "<img_end>"
IGNORE_INDEX      = -100
IMAGE_TOKEN_INDEX = -200
PAD_FOR_EOS       = -300

CONTROLLER_HEART_BEAT_EXPIRATION = 30
LOGDIR = "gradio-logs"
WORKER_HEART_BEAT_INTERVAL = 15
